- name: My Arista Playbook
  hosts: switches
  gather_facts: false

  vars_files:
    - ~/switch.creds

  # changed banner to motd    
  tasks:
  - name: configure the login banner
    eos_banner:
      banner: motd
      text: |
        Congrats this is your motd! You set a banner using an Ansible EOS module.
        Notice how YAML formatting lets us do multi-line
        strings
      state: "{{ herethere }}"

